version: '3'
services:

    haxe:
        restart: always
        build:
            context: ./docker/haxe/
            dockerfile: dockerfile
        environment: 
            KEEP_CONTAINER_ALIVE: "yes"
            RUN_BASH_SCRIPT: "/docker-haxe/script/init.sh"
        volumes:
            - ./docker/shared:/docker-shared
            - ./docker/haxe:/docker-haxe
            - ./crapp-ui:/crapp-ui

    nginx:
        restart: always
        build:
            context: ./docker/nginx/
            dockerfile: dockerfile
            args:
                - LOCAL_DOMAIN=priori.crapp_ui
        volumes:
            - ./crapp-ui/build:/etc/nginx/conf.d/build
        ports:
            - "8283:80"
        depends_on:
            - haxe