FROM nginx:1.25.3-alpine

ARG LOCAL_DOMAIN

ENV NGINX_PORT=80
ENV LOCAL_DOMAIN=$LOCAL_DOMAIN

COPY ./config/config.conf /etc/nginx/template.default.conf
COPY ./config/nginx.conf /etc/nginx/nginx.conf

RUN apk add --no-cache gettext
RUN envsubst "$(printf '${%s} ' $(env | cut -d'=' -f1))" < /etc/nginx/template.default.conf > /etc/nginx/conf.d/default.conf
